from ._compat import text_type as text_type
from .config import AUTH_HEADER_NAME as AUTH_HEADER_NAME, COOKIE_DURATION as COOKIE_DURATION, COOKIE_HTTPONLY as COOKIE_HTTPONLY, COOKIE_NAME as COOKIE_NAME, COOKIE_SECURE as COOKIE_SECURE, ID_ATTRIBUTE as ID_ATTRIBUTE, LOGIN_MESSAGE as LOGIN_MESSAGE, LOGIN_MESSAGE_CATEGORY as LOGIN_MESSAGE_CATEGORY, REFRESH_MESSAGE as REFRESH_MESSAGE, REFRESH_MESSAGE_CATEGORY as REFRESH_MESSAGE_CATEGORY, SESSION_KEYS as SESSION_KEYS, USE_SESSION_FOR_NEXT as USE_SESSION_FOR_NEXT
from .mixins import AnonymousUserMixin as AnonymousUserMixin
from .signals import session_protected as session_protected, user_accessed as user_accessed, user_loaded_from_cookie as user_loaded_from_cookie, user_loaded_from_header as user_loaded_from_header, user_loaded_from_request as user_loaded_from_request, user_needs_refresh as user_needs_refresh, user_unauthorized as user_unauthorized
from .utils import _create_identifier as _create_identifier, _user_context_processor as _user_context_processor, decode_cookie as decode_cookie, encode_cookie as encode_cookie, expand_login_view as expand_login_view, make_next_param as make_next_param
from _typeshed import Incomplete
from typing import (Optional)

class LoginManager:
    anonymous_user: Incomplete
    login_view: Incomplete
    blueprint_login_views: Incomplete
    login_message: Incomplete
    login_message_category: Incomplete
    refresh_view: Incomplete
    needs_refresh_message: Incomplete
    needs_refresh_message_category: Incomplete
    session_protection: Optional[str]
    localize_callback: Incomplete
    unauthorized_callback: Incomplete
    needs_refresh_callback: Incomplete
    id_attribute: Incomplete
    _user_callback: Incomplete
    _header_callback: Incomplete
    _request_callback: Incomplete
    _session_identifier_generator: Incomplete
    def __init__(self, app: Incomplete | None = ..., add_context_processor: bool = ...) -> None: ...
    def setup_app(self, app, add_context_processor: bool = ...) -> None: ...
    def init_app(self, app, add_context_processor: bool = ...) -> None: ...
    def unauthorized(self): ...
    def user_loader(self, callback): ...
    def header_loader(self, callback): ...
    def request_loader(self, callback): ...
    def unauthorized_handler(self, callback): ...
    def needs_refresh_handler(self, callback): ...
    def needs_refresh(self): ...
    def _update_request_context_with_user(self, user: Incomplete | None = ...) -> None: ...
    def _load_user(self): ...
    def _session_protection_failed(self): ...
    def _load_user_from_remember_cookie(self, cookie): ...
    def _load_user_from_header(self, header): ...
    def _load_user_from_request(self, request): ...
    def _update_remember_cookie(self, response): ...
    def _set_cookie(self, response) -> None: ...
    def _clear_cookie(self, response) -> None: ...
    @property
    def _login_disabled(self): ...
    @_login_disabled.setter
    def _login_disabled(self, newvalue) -> None: ...
