# Run tox. https://github.com/marketplace/actions/run-tox-gh-actions
name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Add later: pypy3. use strings so yaml doesn't get smart
        # about floats.
        python-version: ['3.10']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run tox with tox-gh-actions
      uses: ymyzk/run-tox-gh-actions@main
