# Run tox. https://github.com/marketplace/actions/run-tox-gh-actions
name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Add later: pypy3. use strings so yaml doesn't get smart
        # about floats.
        python-version: ['3.10']
    steps:
    - name: Install devel dependencies
      run: >-
        sudo apt install -y gcc git python-minimal python2.7-dev
        libffi-dev libssl-dev make g++ libleveldb-dev librrd-dev
        libxslt1-dev libc-ares-dev libsnappy-dev python-pip
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run tox with tox-gh-actions
      uses: ymyzk/run-tox-gh-actions@main
